Changed project structure and added jar with dependencies
IvanKhomka/homework2 pull request #8
Opened 2024-09-16 23:25 UTC by IvanKhomka

Changed project structure and added jar with dependencies, also changed BusTicketService class structure.

2024-09-17 05:35 UTC, Alexmansar requested changes
@IvanKhomka Please, fix small comments, and also, send pom.xml

2024-09-17 05:35 UTC, Alexmansar commented on src/main/java/andersen/BusTicketService.java
> +    private List<BusTicket> tickets;
move field before the methods

2024-09-17 05:35 UTC, Alexmansar commented on src/main/java/andersen/BusTicketService.java
> +    }
could be separate class

2024-09-17 21:24 UTC, IvanKhomka commented on src/main/java/andersen/BusTicketService.java
> +    private List<BusTicket> tickets;
moved field

2024-09-17 21:26 UTC, IvanKhomka commented on src/main/java/andersen/BusTicketService.java
> +    }
it should be separate class in busticketservice class or new class?

2024-09-18 07:50 UTC, Alexmansar commented on src/main/java/andersen/BusTicketService.java
> +    }
new class, not inner)

2024-09-18 15:48 UTC, IvanKhomka commented on src/main/java/andersen/BusTicketService.java
> +    }
Added new class

2024-09-19 11:47 UTC, Alexmansar approved these changes
@IvanKhomka Could be merged

2024-09-19 11:54 UTC, merged