JDBC Homework
IvanKhomka/homework2 pull request #9
Opened 2024-09-25 23:34 UTC by IvanKhomka

Added solution for jdbc homework

2024-09-26 05:30 UTC, Alexmansar requested changes
@IvanKhomka Hi, In general good job, but I have some general comments. Please, fix it)

2024-09-26 05:30 UTC, Alexmansar commented on src/main/java/jdbctask/Demonstration.java
> +    private static final String password = "82463755";
if we use private static final feilds - we shoul give name like URL, USERNAME...

2024-09-26 05:30 UTC, Alexmansar commented on src/main/java/jdbctask/dao/TicketDao.java
> +        String query = "INSERT INTO Ticket (user_id, ticket_type) VALUES (?, ?::ticket_type);";
use it like constants . In each query 
```
 private static final String url = "jdbc:postgresql://localhost:5432/my_ticket_service_db";
    private static final String username = "postgres";
    private static final String password = "82463755";
```

2024-09-26 05:30 UTC, Alexmansar commented on src/main/java/jdbctask/oldprojectclasses/Ticket.java
> +}
fix formatting

2024-09-26 05:30 UTC, Alexmansar commented on src/main/java/jdbctask/oldprojectclasses/User.java
> +        return creationDate; }
here

2024-09-26 05:30 UTC, Alexmansar commented on src/main/java/jdbctask/dao/UserDao.java
> +    }
please, create new class that should work with connection, and just return preperad one
alo, you can remove 
```
 private final String url;
    private final String username;
    private final String password;
```
and use it in new class

and 
```
 private static final String url = "jdbc:postgresql://localhost:5432/my_ticket_service_db";
    private static final String username = "postgres";
    private static final String password = "82463755";
```
as well should be use in new class
its good way to have separate class for this connection logic

2024-09-27 10:23 UTC, Alexmansar requested changes
@IvanKhomka Hi)) I have another commets)) please have a look)

2024-09-27 10:23 UTC, Alexmansar commented on src/main/java/jdbctask/DBConfig.java
> +    public static final String PASSWORD = "82463755";
move it just to DBConnection

2024-09-27 10:23 UTC, Alexmansar commented on src/main/java/jdbctask/DBConnection.java
> +    }
move before private method

2024-09-27 10:23 UTC, Alexmansar commented on src/main/java/jdbctask/dao/TicketDao.java
> +        String query = "INSERT INTO Ticket (user_id, ticket_type) VALUES (?, ?::ticket_type);";
what about it? If its not clear - just ask)

2024-09-27 10:35 UTC, Alexmansar commented on src/main/java/jdbctask/dao/TicketDao.java
> +        String query = "INSERT INTO Ticket (user_id, ticket_type) VALUES (?, ?::ticket_type);";
String query = "INSERT INTO Ticket (user_id, ticket_type) VALUES (?, ?::ticket_type);";

use as a constant in the class))

2024-09-27 10:35 UTC, Alexmansar commented on src/main/java/jdbctask/DBConfig.java
> +    public static final String PASSWORD = "82463755";
And this toy can set in the constructor here DBConnection

2024-09-27 10:39 UTC, IvanKhomka commented on src/main/java/jdbctask/dao/TicketDao.java
> +        String query = "INSERT INTO Ticket (user_id, ticket_type) VALUES (?, ?::ticket_type);";
Ok, sorry, just did't see this)

2024-09-27 11:09 UTC, Alexmansar approved these changes
@IvanKhomka Could be merged))

2024-09-27 11:11 UTC, merged